# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mas Chataigner
subtitle_de: Im Land der Cèze
subtitle_fr: dans le pays de Cèze
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
#jekyll-assets
assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
    - uploads


defaults:
  #languages
  -
    scope:
      path: ""
    values:
      lang: "de"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
  
#cloudcannon options
_options:
  Bild_2_image:
    width: 120
    height: 90
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
  Bild_3_image:
    width: 120
    height: 90
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
  Bild_4_image:
    width: 90
    height: 120
    resize_style: "cover"
    mime_type: "image/jpeg"
    expandable: true
  Bild_5_image:
    width: 90
    height: 200
    resize_style: "cover"
    expandable: true